


import Authprovider from "./component/Authprovider/Authprovider";
import ClientLayout from "./ClientLayout";
import { Inter as FontSans } from "next/font/google";
import './globals.css';

export const metadata = {
  title: 'CNE',
  description: 'Generated by Next.js',
}

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Authprovider>
          <ClientLayout>
            {children}
          </ClientLayout>
        </Authprovider>
      </body>
    </html>
  )
}




